import { query } from '../lib/db.js'; import { requireAuth } from '../lib/auth.js';
export const resources={
 skills:{table:'skills',fields:['name','category','proficiency','icon','display_order'],order:'display_order ASC'},
 experience:{table:'experience',fields:['job_title','company','location','start_date','end_date','current','description','achievements','display_order'],order:'display_order ASC'},
 education:{table:'education',fields:['institution','degree','field','start_date','end_date','grade','description','display_order'],order:'display_order ASC'},
 certifications:{table:'certifications',fields:['name','issuer','issue_date','credential_id','credential_url','description','icon','display_order'],order:'display_order ASC'},
 services:{table:'services',fields:['title','description','icon','display_order','published'],order:'display_order ASC'},
 projects:{table:'projects',fields:['title','slug','short_description','case_study','image_url','technologies','github_url','live_demo_url','status','featured','published','display_order'],order:'display_order ASC'}
};
const normalize=(field,v)=>['achievements','technologies'].includes(field)?(Array.isArray(v)?JSON.stringify(v):v||'[]'):v;
export async function listOrCreate(req,res,key){const r=resources[key];if(!r)return res.status(404).json({error:'Not found'});try{if(req.method==='GET'){const q=await query(`SELECT * FROM ${r.table} ORDER BY ${r.order}`);return res.json(q.rows);}if(!['POST'].includes(req.method))return res.status(405).json({error:'Method not allowed'});if(!(await requireAuth(req,res)))return;const b=req.body||{};const values=r.fields.map(f=>normalize(f,b[f]));const cols=r.fields.join(',');const marks=r.fields.map((_,i)=>`$${i+1}`).join(',');const q=await query(`INSERT INTO ${r.table} (${cols}) VALUES (${marks}) RETURNING *`,values);return res.status(201).json(q.rows[0]);}catch(e){console.error(e);return res.status(500).json({error:'Database operation failed'});}}
export async function updateOrDelete(req,res,key,id){const r=resources[key];if(!(await requireAuth(req,res)))return;try{if(req.method==='DELETE'){await query(`DELETE FROM ${r.table} WHERE id=$1`,[id]);return res.json({ok:true});}if(req.method!=='PUT')return res.status(405).json({error:'Method not allowed'});const b=req.body||{};const pairs=r.fields.map((f,i)=>`${f}=$${i+1}`);const values=r.fields.map(f=>normalize(f,b[f]));values.push(id);const q=await query(`UPDATE ${r.table} SET ${pairs.join(', ')}, updated_at=now() WHERE id=$${values.length} RETURNING *`,values);if(!q.rows[0])return res.status(404).json({error:'Not found'});return res.json(q.rows[0]);}catch(e){console.error(e);return res.status(500).json({error:'Database operation failed'});}}
